// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;


import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;
public class AgoraTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "Drivers/chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();

    driver.get("https://www.agora.co.il/");
    driver.manage().window().setSize(new Dimension(1600, 860));
    {
      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("#dialog_overlayTd > div > div.dialog_closeButton")));
      driver.findElement(By.cssSelector("#dialog_overlayTd > div > div.dialog_closeButton")).click();
    }


  }
  @After
  public void tearDown() {
    driver.close();
    driver.quit();
  }
  @Test
  public void showitemsfordelivery() {
    driver.get("https://www.agora.co.il/");
    driver.manage().window().setSize(new Dimension(1280, 680));
    {
      WebDriverWait wait = new WebDriverWait(driver,Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("categoryRuler")));
    }
    //assertThat(driver.findElement(By.id("categoryRuler")).getText(), is("מוצרי חשמל\\\\nריהוט וכלי בית\\\\nספרים ומדיה\\\\nבגדים ואופנה\\\\nתחביבים וספורט\\\\nלתינוק ולילד\\\\nסיוע חברתי\\\\nשונות"));
    driver.findElement(By.cssSelector(".categoryLink:nth-child(1) > .categoryIcon")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver,Duration.ofSeconds(30));
      wait.until(ExpectedConditions.textToBe(By.cssSelector("h1"), "מוצרי חשמל - לוח יד שניה למסירה בחינם"));
    }
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("מוצרי חשמל - לוח יד שניה למסירה בחינם"));
    driver.findElement(By.linkText("הצג חפצים מבוקשים")).click();
    assertThat(driver.findElement(By.linkText("הצג חפצים למסירה")).getText(), is("הצג חפצים למסירה"));
    //driver.close();
  }
  @Test
  public void categoryview() {
    driver.get("https://www.agora.co.il/");
    driver.manage().window().setSize(new Dimension(1280, 680));
    driver.findElement(By.cssSelector("#buttonCategories > .buttonImage")).click();
    driver.findElement(By.cssSelector("#buttonCategories > .buttonImage")).click();
    driver.findElement(By.id("siteBody")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver,Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("categoryRuler")));
    }
    assertThat(driver.findElement(By.linkText("מוצרי חשמל")).getText(), is("מוצרי חשמל"));
    //driver.close();
  }
  @Test
  public void filterbycity() {
    driver.get("https://www.agora.co.il/");
    driver.manage().window().setSize(new Dimension(1280, 680));
    {
      WebDriverWait wait = new WebDriverWait(driver,Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("categoryRuler")));
    }
    //assertThat(driver.findElement(By.id("categoryRuler")).getText(), is("מוצרי חשמל\\\\nריהוט וכלי בית\\\\nספרים ומדיה\\\\nבגדים ואופנה\\\\nתחביבים וספורט\\\\nלתינוק ולילד\\\\nסיוע חברתי\\\\nשונות"));
    driver.findElement(By.cssSelector(".categoryLink:nth-child(1) > .categoryIcon")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver,Duration.ofSeconds(30));
      wait.until(ExpectedConditions.textToBe(By.cssSelector("h1"), "מוצרי חשמל - לוח יד שניה למסירה בחינם"));
    }
    int delayBetweenActions = 2000; // Delay in milliseconds
    driver.findElement(By.id("takeCityInput")).click();
    driver.findElement(By.id("takeCityInput")).sendKeys("בית שמש");
    try {
      Thread.sleep(delayBetweenActions);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    driver.findElement(By.cssSelector("#takeCity > li")).click();
    driver.findElement(By.id("siteBody")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver,Duration.ofSeconds(30));
      wait.until(ExpectedConditions.textToBe(By.cssSelector("h1"), "מוצרי חשמל בבית שמש - לוח יד שניה למסירה בחינם"));
    }
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("מוצרי חשמל בבית שמש - לוח יד שניה למסירה בחינם"));
    //driver.close();
  }
  @Test
  public void categoryselection() {
    driver.get("https://www.agora.co.il/");
    driver.manage().window().setSize(new Dimension(1280, 680));
    {
      WebDriverWait wait = new WebDriverWait(driver,Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("categoryRuler")));
    }
    driver.findElement(By.cssSelector(".categoryLink:nth-child(1) > .categoryIcon")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver,Duration.ofSeconds(30));
      wait.until(ExpectedConditions.textToBe(By.cssSelector("h1"), "מוצרי חשמל - לוח יד שניה למסירה בחינם"));
    }
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("מוצרי חשמל - לוח יד שניה למסירה בחינם"));
  }
  @Test
  public void selectasubcategory() {
    driver.get("https://www.agora.co.il/");
    driver.manage().window().setSize(new Dimension(1280, 680));
    {
      WebDriverWait wait = new WebDriverWait(driver,Duration.ofSeconds(30));
      wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("categoryRuler")));
    }
    //assertThat(driver.findElement(By.id("categoryRuler")).getText(), is("מוצרי חשמל\\\\nריהוט וכלי בית\\\\nספרים ומדיה\\\\nבגדים ואופנה\\\\nתחביבים וספורט\\\\nלתינוק ולילד\\\\nסיוע חברתי\\\\nשונות"));
    driver.findElement(By.cssSelector(".categoryLink:nth-child(1) > .categoryIcon")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver,Duration.ofSeconds(30));
      wait.until(ExpectedConditions.textToBe(By.cssSelector("h1"), "מוצרי חשמל - לוח יד שניה למסירה בחינם"));
    }
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("מוצרי חשמל - לוח יד שניה למסירה בחינם"));
    driver.findElement(By.cssSelector(".subject:nth-child(1) > .subCategory:nth-child(2) > h3")).click();
    {
      WebDriverWait wait = new WebDriverWait(driver,Duration.ofSeconds(30));
      wait.until(ExpectedConditions.textToBe(By.cssSelector("h1"), "טוסטרים וטוסטר אובן"));
    }
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("טוסטרים וטוסטר אובן"));
    //driver.close();
  }
}
